In [28]:
import numpy as np
path = "F:/1/Classic_machine_learning-master/data_set/datingTestSet.txt"

In [29]:
data = []
labels = []
open_file = open(path,mode='r',encoding='utf-8')
STR = open_file.read()
lines = STR.split('\n')
for line in lines[0:200]:
    f_1 = line.split('\t')
    x1,x2,x3,label = float(f_1[0]),float(f_1[1]),float(f_1[2]),f_1[3]
    data.append([x1,x2,x3])
    labels.append(label)
    
data = np.array(data)
labels = np.array(labels)
print(data)

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 [7.5136000e+04 1.3147394e+01 4.2896400e-01]
 [3.8344000e+04 1.6697880e+00 1.3429600e-01]
 [7.2993000e+04 1.0141740e+01 1.0329550e+00]
 [3.5948000e+04 6.8307920e+00 1.2131920e+00]
 [4.2666000e+04 1.3276369e+01 5.4388000e-01]
 [6.7497000e+04 8.6315770e+00 7.4927800e-01]
 [3.5483000e+04 1.2273169e+01 1.5080530e+00]
 [5.0242000e+04 3.7234980e+00 8.3191700e-01]
 [6.3275000e+04 8.3858790e+00 1.6694850e+00]
 [5.5690000e+03 4.8754350e+00 7.2865800e-01]
 [5.1052000e+04 4.6800980e+00 6.2522400e-01]
 [7.7372000e+04 1.5299570e+01 3.3135100e-01]
 [4.3673000e+04 1.8894610e+00 1.9128300e-01]
 [6.1364000e+04 7.5167540e+00 1.2691640e+00]
 [6.9673000e+04 1.4239195e+01 2.6133300e-01]
 [1.5669000e+04 0.0000000e+00 1.2501850e+00]
 [2.8488000e+04 1.0528555e+01 1.3048440e+00]
 [6.4870000e+03 3.5402650e+00 8.2248300e-01]
 [3.7708000e+04 2.9915510e+00 8.3392000e-01]
 [2.262000

In [30]:
max_ = np.max(data,axis=0)
min_ = np.min(data,axis=0)

In [31]:
new_data = (data - min_) / (max_ - min_)

In [39]:
norm_data = data
norm_data

array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01],
       [1.4488000e+04, 7.1534690e+00, 1.6739040e+00],
       [2.6052000e+04, 1.4418710e+00, 8.0512400e-01],
       [7.5136000e+04, 1.3147394e+01, 4.2896400e-01],
       [3.8344000e+04, 1.6697880e+00, 1.3429600e-01],
       [7.2993000e+04, 1.0141740e+01, 1.0329550e+00],
       [3.5948000e+04, 6.8307920e+00, 1.2131920e+00],
       [4.2666000e+04, 1.3276369e+01, 5.4388000e-01],
       [6.7497000e+04, 8.6315770e+00, 7.4927800e-01],
       [3.5483000e+04, 1.2273169e+01, 1.5080530e+00],
       [5.0242000e+04, 3.7234980e+00, 8.3191700e-01],
       [6.3275000e+04, 8.3858790e+00, 1.6694850e+00],
       [5.5690000e+03, 4.8754350e+00, 7.2865800e-01],
       [5.1052000e+04, 4.6800980e+00, 6.2522400e-01],
       [7.7372000e+04, 1.5299570e+01, 3.3135100e-01],
       [4.3673000e+04, 1.8894610e+00, 1.9128300e-01],
       [6.1364000e+04, 7.5167540e+00, 1.2691640e+00],
       [6.9673000e+04, 1.4239195e+01, 2.6133300e-01],
       [1.5669000e+04, 0.000

In [41]:
def split_data(X,y,pre):
train_x,train_y,test_x,test_y = split_data(norm_data,y,0.3)

NameError: name 'split_data' is not defined

In [35]:
data_train = train.reshape((60000,28*28)) 
print(x_train.shape)0

NameError: name 'tabels' is not defined